### ISSUE TITLE
problem with import

### ISSUE THREAD

**Issue by saman** [didierfranc/react-code-splitting#10]
Thanks for the useful component.

After using this solution in my project I've got this error on build:
```
ERROR in ./src/pages/App.jsx
Module build failed: SyntaxError: Unexpected token (32:34)

>  const RegLib = () => <Async load={import('../container/RegLib')} />;
                                     ^
const App = ({ user, setUser }) => (
<Router>
```

I built [that sample](https://github.com/didierfranc/redux-react-starter/) you created, it works fine.

Do you have any suggestion?
Thanks.

**Comment by MCluck90** [comment]
Asynchronous imports are not standardized so you currently require a couple of plugins to make it work. Assuming you're using Babel and Webpack, you'll need the [`dynamic-import-webpack`](https://www.npmjs.com/package/babel-plugin-dynamic-import-webpack) plugin and the [`syntax-dynamic-import`](https://www.npmjs.com/package/babel-plugin-syntax-dynamic-import) plugin.
