### ISSUE TITLE
How to show loading indicator for people on slow/unstable network?

### ISSUE THREAD

**Issue by kdenz** [didierfranc/react-code-splitting#2]
Code splitting is almost instantaneous on faster networks, but I'm concerned that when loading time is significant, is there a simple way to display a loading indicator somewhere? Right now I'm just thinking of displaying a loading indicator in place of the link upon onClick event.

**Comment by obregon08** [comment]
@kdenz I pushed a PR https://github.com/didierfranc/react-code-splitting/pull/12 that solves that problem

**Comment by didierfranc** [comment]
Personally I handle that outside of <Async /> component with a <TryCatch /> component as I already written we'll try to keep this project very very simple. Don't hesitate to fork it if you want to add some feature 😉
