### ISSUE TITLE
Expression expected?

### ISSUE THREAD

**Issue by aethant** [didierfranc/react-code-splitting#3]
I'm trying out this module, and it is working, however, I get the following error in my IDE (VS Code):

    const MyAsyncComponent = props => <Async load={import( '../components/myasynccomponent' )} componentProps={props} />

Specifically, it points to the `import` statement itself.

I'm trying to follow the sample code as provided, and the component DOES load as expected. Is this an issue with my linting or IDE setup, or otherwise?  If so, any idea how to resolve it reporting the error? Thanks!

**Comment by Gal-Brenner** [comment]
Any answer about this?

**Comment by didierfranc** [comment]
It seems working for a lot of people around me

Is this turned off in your conf ? https://github.com/didierfranc/vscode-react-intellisense/blob/master/.vscode/settings.json#L5

**Comment by pawarvijay** [comment]
Here `System.import()` Can be used But it will Be depreciated in coming time
And only `import()` will be used
For this you can use [import()](https://babeljs.io/docs/plugins/syntax-dynamic-import/) currently  this in stage3 at Tc39
