### ISSUE TITLE
Not loading CSS propertly

### ISSUE THREAD

**Issue by matheusml** [didierfranc/react-code-splitting#4]
I'm using this plugin, exactly like in the docs, to setup route-based code-splitting:

```javascript
import React from "react";
import { BrowserRouter as Router, Route } from "react-router-dom";
import Async from "react-code-splitting";

import Article from "../article/Article";

const Home = () => <Async load={import("../home/Home")} />;

const Routes = () => (
  <Router>
    <div>
      <Route exact path="/" component={Home} />
    </div>
  </Router>
);

export default Routes;

```

But for some reason, the CSS aren't loading propertly.
Btw, I'm using CSS Modules.

This is using the plugin:

![](http://i.imgur.com/DSm9ZK7.png)

This is without the plugin:

![](http://i.imgur.com/FSl1JOq.png)

**Comment by didierfranc** [comment]
Hi, you should try to add componentProps to pass down your props

→ https://github.com/didierfranc/react-code-splitting#with-code-splitting

**Comment by matheusml** [comment]
I found the solution, it have nothing to do with this lib.
I simply had to put ```allChunks: true``` on ExtractTextPlugin.
