### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by wilbert-abreu** [didierfranc/react-code-splitting#5]
@didierfranc Any insight on how this would would with a server rendered app using React Router?

Here's what I have so far that "works", but because of the `this.forceUpdate()` most of the app is not showing up server side. 

```
  getComponent={(nextState, callback)  => {
        callback(null, props => <Async load={
          import("../../components/pages/home" /* webpackChunkName: "home" */)
        } componentProps={props}/>);
```

**Comment by didierfranc** [comment]
Is it possible for you to make a minimal sample I'll fix that asap ;)

**Comment by davidfurlong** [comment]
@didierfranc any attempt to server side render using the `Async` HOC gives me 
```Warning: forceUpdate(...): Can only update a mounting component. This usually means you called forceUpdate() outside componentWillMount() on the server. This is a no-op. Please check the code for the Async component.```

**Comment by didierfranc** [comment]
Do you have something like that for the server part ? https://www.npmjs.com/package/babel-plugin-transform-system-import-commonjs

**Comment by davidfurlong** [comment]
@didierfranc yep I use https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-commonjs which is part of the `babel` `es2015` preset

**Comment by davidfurlong** [comment]
I think I found the issue https://github.com/davidfurlong/react-code-splitting
But this fork isn't really PR ready because I removed `PropTypes` due to an issue with the `Promise` constructor being different on client/server

**Comment by didierfranc** [comment]
It will be great to merge your enhancements if you want to make a PR

**Comment by neoziro** [comment]
Server-side rendering + code splitting is not easy, there si several things to do. If you are interested, [I explained it in an article](https://medium.com/smooth-code/introducing-loadable-components-%EF%B8%8F-646dd3ab0aa6).

**Comment by didierfranc** [comment]
I think I'll draft a babel-plugin it's the easiest way I think to make it easy

**Comment by neoziro** [comment]
@didierfranc I think a babel-plugin is not the way to do it, relying on Babel is not very scalable. Babel is only a way to use features not available in the language, but not a way to implement new features.

**Comment by didierfranc** [comment]
Just to have a simple way to convert import() for SSR ;)

**Comment by neoziro** [comment]
@didierfranc already done https://github.com/airbnb/babel-plugin-dynamic-import-node

**Comment by neoziro** [comment]
Also if you are using Webpack with "node" as target, it does exactly the same thing.

**Comment by didierfranc** [comment]
Oh 😻

**Comment by didierfranc** [comment]
I never tested https://github.com/didierfranc/react-code-splitting with ssr so if it's working that two solution an update of the readme could definitely close this issue

**Comment by neoziro** [comment]
@didierfranc not so simple, I do it with [loadable-components](https://github.com/smooth-code/loadable-components#server-side-rendering), and it requires several thing. It's detailed in [the article](https://medium.com/smooth-code/introducing-loadable-components-%EF%B8%8F-646dd3ab0aa6).

**Comment by didierfranc** [comment]
Yes that's what I thought, I don't forget the magic babel-plugin solution

**Comment by didierfranc** [comment]
I think we can definitely close this, for server side rendering @neoziro [loadable-component](https://github.com/smooth-code/loadable-components#server-side-rendering) proposes a great approach 😉

We'll probably keep this project (react-code-splitting) as the simplest approach for code splitting. For more advanced feature try some other lib !

**Comment by neoziro** [comment]
@didierfranc thanks for mentioning [loadable-components](https://github.com/smooth-code/loadable-components#server-side-rendering)!
