### ISSUE TITLE
React-Router doesn't pass route parameters to Async components

### ISSUE THREAD

**Issue by wsrast** [didierfranc/react-code-splitting#6]
Any  `<Route/>` that uses a path matcher containing route parameters will not pass those params to the React Component that's loaded via `<Async/>`. Example
`const EditForm = () => {
		return <Async load={import('./Main/Form/EditForm/EditForm')}/>;
	};`

`<Route path="edit/:id" component={EditForm}/>`

`constructor(props) {
    super(props);
    this.state = {formId: props.routeParams.id}
}`

The above reference to props.routeParams.id will fail with an exception, as props.routeParams is undefined. Using normal imports, the same code works, and props.routeParams is properly populated.

`import EditForm from './Main/Form/EditForm/EditForm';`

**Comment by didierfranc** [comment]
https://github.com/didierfranc/react-code-splitting/issues/7 should solve this issue don't hesitate to reopen an issue if the problem persist
