### ISSUE TITLE
how use componentProps?

### ISSUE THREAD

**Issue by nato90** [didierfranc/react-code-splitting#7]
How to pass a props with componentProps, any explicit example?

**Comment by didierfranc** [comment]
https://gist.github.com/didierfranc/33b1ed7a27210c7183d58a69fc31b764

**Comment by nato90** [comment]
Hello! @didierfranc, but for example how would the MyAsyncComponent component receive the props this.props.url?

Can you pass a state? And if so, how would the component receive it?

**Comment by didierfranc** [comment]
```js
const AsyncLoadedFatComponent = (props) => (
  <Async load={import('FatComponent')} componentProps={props} />
)

<AsyncLoadedFatComponent url="http://..." />
```

```js
class FatComponent extends Component {
  render() {
    <a href={this.props.url}>Click me </a>
  }
}
```
