### ISSUE TITLE
Issue in IE10/Edge

### ISSUE THREAD

**Issue by slclarkdev** [didierfranc/react-code-splitting#9]
SCRIPT5009: 'Promise' is undefined

From 
Async.propTypes = {
  load: _propTypes2.default.instanceOf(Promise).isRequired
};

I've loaded the es6-promise polyfill() in the router, but still getting this error.  I'm wondering if you have to add the poly fill to your code?

**Comment by didierfranc** [comment]
Yes you need a promise polyfill.

My preference goes to https://polyfill.io, it's what we are using with [redux-react-starter](https://github.com/didierfranc/redux-react-starter/blob/master/webpack/template.html#L24)

```
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
```
